### ISSUE TITLE
Advanced converter

### ISSUE THREAD

**Issue by AMIDIBOSS** [Electrical-Age/ElectricalAge#736] opened 2017-05-19 20:27 UTC
I think we shall have more expensive, end game, 16:1 ratio converter.
Instead of placing two 4:1 ratio transformers.
Ground and polemount. I'd be glad if that's possible.

**Comment by OmegaHaxors** [comment] 2017-05-26 03:34
I support this in the form of a type of variac. Building auto-converters in world is absolutely terrible even though it's possible; due to the voltage and amperage limits on the wires, either the primary fails due to over-amping or the secondary fails due to over-volting and there's no reliable way to remedy that.

I would prefer the wires be improved to allow this to be possible, but it's probably easier to balance to simply make it as a new block which can be manipulated by signals.

**Comment by AMIDIBOSS** [comment] 2017-05-27 18:21
I didn't meant variacs, but hey are a good idea, too

**Comment by Baughn** [comment] 2017-10-13 18:36
Duplicate of #749

**Closed as completed by Baughn** 2017-10-13 18:36 UTC
Labels: duplicate, new item request
