### ISSUE TITLE
crash when using Miner

### ISSUE THREAD

**Issue by GWLAN** [Electrical-Age/ElectricalAge#511] opened 2016-08-29 08:15 UTC
i just put a drill into the miner
[crash-2016-08-29_14.05.22-client.txt](https://github.com/Electrical-Age/ElectricalAge/files/441968/crash-2016-08-29_14.05.22-client.txt)

**Comment by cm0x4D** [comment] 2016-08-29 08:24
OK I see a potential problem, which language are you using?

**Comment by GWLAN** [comment] 2016-08-29 09:03
chinese

**Comment by cm0x4D** [comment] 2016-08-29 09:08
The problem is that the Chinese translation has only one line and in code we are waiting for two.
Ii is fixed in the develop branch and the fix will be part of the next release. 

In the meantime you can switch to english to avoid the crash if you want...

**Comment by cm0x4D** [comment] 2016-08-29 09:09
Thanks for issue.

**Closed as completed by cm0x4D** 2016-08-29 09:09 UTC

**Comment by AMIDIBOSS** [comment] 2016-08-29 09:15
> the next release.

How long it'll take. When we can download it?

**Comment by cm0x4D** [comment] 2016-08-29 09:33
Thanks to @Safranil you can download the latest builds of the development branch here:

http://ci.safranil.fr:8080/job/ElectricalAge/lastSuccessfulBuild/artifact/build/libs/ElectricalAge-1.12.0.jar

But use it on your own risk and backup your maps...

I have just some missing recipes that need to be done, otherwise nothing is really blocking a release form my side, on the other hand this would not be that a big release... 

@metc: Would probably make sense to add the link to the development build if @Safranil gives us the permission do do so...

**Comment by Baughn** [comment] 2016-08-29 10:03
@cm0x4D I don't see why he shouldn't, but if he doesn't, poke me about it and I'll set up a build server on my side.

**Comment by metc** [comment] 2016-08-29 11:13
Sorry but Travis + Bintray do already the job ? Or what's different in this case ?

**Comment by cm0x4D** [comment] 2016-08-29 11:15
Bintray does not work that well for snapshots (it refuses artifacts with the same version) , for releases it would be great though

**Comment by AMIDIBOSS** [comment] 2016-08-31 16:31
I downloaded the development version linked up. from first 5 minutes of playing I say, theres no bugs yet.
But I need to ask, how old is this version? There are no utility poles, no fuses, no other cool features github was loud about. That's sad.

**Comment by cm0x4D** [comment] 2016-08-31 19:58
> But I need to ask, how old is this version? There are no utility poles, no fuses, no other cool features github was loud about. That's sad.

Ok, the fuses feature is not merged yet into develop, for the utility poles I do not know the status, but there is no pull request yet. But we have fixed quite a bunch of bugs and these new things are already merged into develop branch:
- Steam turbine can be throttled
- Gaz turbine
- New mechanical items like joints, flywheels and tachometer
- Battery powered fire alarm
- Recipes for logic gates

The fuses feature is almost finished, I am a bit uncertain about the recipes for the items, but I would like to merge it still this week...

**Comment by AMIDIBOSS** [comment] 2016-09-01 04:42
Okay

**Comment by Baughn** [comment] 2016-09-01 11:28
The utility pole were the first thing I coded for EA, and needed a rewrite. I've been working on that, so they might be ready for a PR this weekend.

**Comment by AMIDIBOSS** [comment] 2016-09-01 17:21
I can't wait for them, so i can make my server way more realistic! But before i go, may i ask two questions?
1. How long the distances between poles could be.
2. What time zone you live in?

**Comment by Safranil** [comment] 2016-09-08 06:28
Hi @cm0x4D,

No problem for me :). I can give you an access to manually build the project if you want.

I can also try to build each branch if necessary.

PS : You can remove the port of the URL : http://ci.safranil.fr/job/ElectricalAge/lastSuccessfulBuild/artifact/build/libs/ElectricalAge-1.12.0.jar

**Comment by cm0x4D** [comment] 2016-09-08 06:30
Thanks @Safranil. Snapshots of development branch is fine for the moment.

**Comment by Safranil** [comment] 2016-09-08 06:31
Ok
