### ISSUE TITLE
Toroidal Transformers

### ISSUE THREAD

**Issue by yannic312** [Electrical-Age/ElectricalAge#293] opened 2015-09-18 21:09 UTC
Please add Toroidal transformers, which could look like this:
![toroidal transformer](https://cloud.githubusercontent.com/assets/11148623/9971178/30da1a4a-5e5a-11e5-9824-2ede65f63c7e.jpg)

**Comment by Baughn** [comment] 2015-09-18 23:04
Is there any difference between these and the current transformers except for looks?

Note that the simulation is wholly DC; the current transformers are actually buck-boost circuits, sort of.

**Comment by ghost** [comment] 2015-09-19 00:20
Realmente o Baughn tem razão, tem alguma diferença deste transformador para o outro?

E Baughn na verdade tem sim a simulação de AC/DC só a lógica é bem complicada de entender, como exemplo a rede é AC mas quando adicionamos uma bateria que é DC (Sabemos disso porque tem o + e -) mas é só pensar que na bateria tem um "Conversor" interno de AC para DC e vice - versa. Assista meus vídeos no canal https://www.youtube.com/user/whilebr que explico bem uma lógica para entender melhor e compreender a simulação.

**Comment by Baughn** [comment] 2015-09-19 02:49
No, I'm pretty sure... I've read quite a lot of the code by now, and I've yet to see even a hint of any AC in there. It's DC as far as the eye can see.

The transformers can be confusing, yes, since those don't exist in DC. Internally to the simulation they're a pretty complicated process that effectively works as buck/boost, with huge internal capacitance.

I don't understand Portugese, so I can't look at that youtube channel.

**Comment by yannic312** [comment] 2015-09-19 11:17
hmm, as I know, toroidal transformers are more efficient, but also have an higher inrush current than "normal" transformers which sometimes causes an circuit breaker to trip off, which can be very annoying... (if that is wrong, someone pls correct me)

**Comment by yannic312** [comment] 2015-09-19 11:19
Also, would it be possible to make a circuit that has DC Input and outputs something like AC or so?

**Comment by Baughn** [comment] 2015-09-19 17:23
AC simply doesn't exist in the system at all. It'd need to be added from scratch, and I don't know that it's very useful. High-voltage DC is problematic in the real world, but in an idealized environment like this one it's actually rather superior to AC.

**Comment by yannic312** [comment] 2015-10-09 20:50
Other Idea, what about Tesla coils?

**Comment by lambdaShade** [comment] 2015-12-29 09:36
The current model of the transformer is quite symbolic but misleads users (AC vs DC).
I plan to redraw this very old "transformator.blend" model. I will look more like a big DC/DC converter device with a visible transformer.

**Comment by cm0x4D** [comment] 2016-12-08 21:44
Duplicate of #237

**Closed as completed by cm0x4D** 2016-12-08 21:44 UTC
Labels: enhancement, new item request
