### ISSUE TITLE
Minecraft "crashes" when trying to load world

### ISSUE THREAD

**Issue by Vankka** [Electrical-Age/ElectricalAge#469] opened 2016-06-30 13:46 UTC
The game can't go to the singleplayer / can't start server

Version: ElectricalAge_BETA-1.11_r51

Server: http://pastebin.com/HTkZ4vum

Client: http://pastebin.com/2FMaxETW

**Comment by cm0x4D** [comment] 2016-06-30 14:09
Probably a duplicate of #451. It is fixed in develop branch and will be included in the next release.

Was there another instance of Minecraft running or any application that listens to TCP port 1502?
Or did you change the Modbus TCP port in  the config file?

**Comment by Vankka** [comment] 2016-07-02 21:33
Doesn't seem like there is anything in port 1502

Config file:

 # Configuration file

balancing {
    D:ElnToIndustrialCraftConversionRatio=0.3333333333333333
    D:ElnToOpenComputerConversionRatio=0.13333333333333333
    D:ElnToThermalExpansionConversionRatio=1.3333333333333333

```
# Maximum horizontal distance from autominer that will be mined
I:autominerRange=10
I:fuelGeneratorPowerFactor=1
I:heatTurbinePowerFactor=1
I:solarPannelPowerFactor=1
I:waterTurbinePowerFactor=1
I:windTurbinePowerFactor=1
```

}

battery {
    # How many days it takes for a battery to decay half way
    I:batteryHalfLife=2
}

compatibility {
    B:ComputerProbeEnable=true
    B:ElnToOtherEnergyConverterEnable=true
}

debug {
    B:enable=false
}

dictionary {
    B:tungsten=false
}

entity {
    B:killMonstersAroundLamps=true
    I:killMonstersAroundLampsRange=9
    I:replicatorId=-1
    B:replicatorPop=true
    D:replicatorPopWhenThunderPerSecond=0.008333333333333333
}

fuelgenerator {
    I:tankCapacityInSecondsAtNominalPower=1200
}

gameplay {
    B:explosion=true
}

general {
    B:analyticsEnable=true
    S:playerUUID=0d52c6c5-54a3-46cf-b28f-e0744add294c
    B:versionCheckEnable=true
}

lamp {
    D:carbonLifeInHours=6.0
    D:economicLifeInHours=64.0
    D:incandescentLifeInHours=16.0
    D:ledLifeInHours=512.0
}

mapgenerate {
    B:cinnabar=true
    B:copper=true
    B:forceOreRegen=false
    B:lead=true
    B:tungsten=true
}

modbus {
    B:enable=false
}

simulation {
    D:cableRsFactor=1.0
    I:electricalFrequency=20
    I:electricalInterSystemOverSampling=50
    I:thermalFrequency=400
}

wireless {
    I:txRange=32
}

xrayscannerconfig {
    B:addOtherModOreToXRay=true
    B:canBeCrafted=true
    D:rangeInBloc=5.0
}

**Comment by Vankka** [comment] 2016-07-02 21:41
The "Issue with ModBus" is getting:
cpw.mods.fml.common.LoaderException: java.net.BindException: Address already in use

i'm only getting what is on pastebin and fml loading before that

**Comment by cm0x4D** [comment] 2016-07-03 17:50
It is certainly the same as #451. 

It is just another error message. Maybe there is a firewall that prevent the socket to start listening or the error message on windows is just different.

It is already fixed in dev and the fix will be part of the next release.

**Closed as completed by cm0x4D** 2016-07-03 17:50 UTC
