### ISSUE TITLE
I miss the progress

### ISSUE THREAD

**Issue by Nikolai521** [Electrical-Age/ElectricalAge#672] opened 2017-02-22 15:28 UTC
Hello, this is the first time I'm in github and I'm using google translator because I speak Spanish in order

I wanted to tell you that lately I have a problem with saving the map yesterday I was doing all the afternoon making a house and I had to put a lot and then close minecraft since I had to eat and when I opened it I found that everything I did with electrical age disappeared. Everything except the mod and I said "Maybe I kept it wrong" and I thought to put a single cable and save the game but when I opened it was no longer.

Well this is driving me crazy try to create another world to see if it solved the problem but not things disappear, I hope to fix  

regards

**Comment by cm0x4D** [comment] 2017-02-22 15:35
Do you have the console output?

**Comment by Nikolai521** [comment] 2017-02-22 15:38
No,The only thing that happens to me is that everything disappears when loading the game and has me crazy

**Comment by cm0x4D** [comment] 2017-02-22 15:42
Which version of the mod do you use? And which forge and Minecraft version?

**Comment by Nikolai521** [comment] 2017-02-22 15:45
Electrical Age 1.14.1
Minecraft 1.7.10
forge 10.13.4.1448

**Comment by cm0x4D** [comment] 2017-02-22 15:51
Your forge version is pretty outdated, use 1614 or never.

Maybe you can do another test with just some cables and report the back if that fixes the problem?

**Comment by Nikolai521** [comment] 2017-02-22 15:52
Ok I'll update the forge later I'll tell you if it fits

**Comment by Nikolai521** [comment] 2017-02-22 17:23
Well I just installed minecraft and install the latest version of forge but at the start of the game I start to create the power generators after I left and enter again and surprise DISAPPEARED EVERYTHING I HAD done, my eyes went white and I'm sad for not To be able to do what I want because it clears me I hope to have it fixed

**Comment by Nikolai521** [comment] 2017-02-22 17:25
I'm seeing the issues and a while ago someone else with the same problem appeared the title says "Placed blocks and items disappear on world reload." is a bug of the last version

**Comment by cm0x4D** [comment] 2017-02-22 18:33
Duplicate of #673

**Closed as completed by cm0x4D** 2017-02-22 18:33 UTC
Labels: bug, duplicate, needs more info
