### ISSUE TITLE
BETA-1.8_r35 200v turbine no voltage

### ISSUE THREAD

**Issue by tvk1372** [Electrical-Age/ElectricalAge#99] opened 2014-08-11 22:10 UTC
Hi!
I found 2 issues
I found some issue when I idle stress test the 200v turbine in the new r35 relase! 
![2014-08-11_23 57 28](https://cloud.githubusercontent.com/assets/8401485/3883565/d9c1335a-21a2-11e4-9bd2-e795e00bc136.png)
(When I don't put anything to the end of the wire,the voltage doesn't rise just the heat)
And the second issue is when I use shaders mod and I want to use the HUB to cross wires,I cant see the selected lines on the HUB so I dont know did I chose the correct line to the wires.
i see only white lines on it,but I select the cross lines
![2014-08-12_00 06 55](https://cloud.githubusercontent.com/assets/8401485/3883646/f261a466-21a3-11e4-919b-0ee7eed104d7.png)

**Comment by JPitman97** [comment] 2014-08-11 22:45
We will look into the first problem but the 2nd one is due to the way Shaders mod renders blocks/items and i don't think it would be possible to resolve this our side.
Cheers for pasting the issue :)
   -Shadow

**Comment by Dolu1990** [comment] 2014-08-11 22:52
Yes thanks for issue :D
hmm yes it's shader issue, i add that to todolist,
But for turbine bug, it's strang :(  If you reload the map, the bug appear again ?
If it's the case, could you send me the map ? (I have tested, and i can't reproduct this bug)

**Comment by Dolu1990** [comment] 2014-08-11 22:57
Ahhh i have successfuly reproduct it : D cool. i explore this bug now.

**Comment by Dolu1990** [comment] 2014-08-11 23:09
Oky, this bug was due to  the turbine math, 64 bit floating point calculation has not the suffisant accurancy XD
It's now fixed and updated in next release.
Don't worry about that in r35, it's nothing critical because this bug can only occure when nothing is connected to the turbine :)

**Comment by tvk1372** [comment] 2014-08-12 00:01
Thanks you!

**Comment by Dolu1990** [comment] 2014-08-12 17:20
For graphical issue, in next update there is some improvment (xray scanner now is not breaked by shader mods)
But for the hub issue, i had successfuly reproduct it with SEUS pack lite, but realy it's a strang bug :(

**Comment by tvk1372** [comment] 2014-08-12 20:51
Thanks Dolu1990!
Its not a big problem of shaders mod, I turn of when I bulid.
But I find a funny but a good thing for me when I continue the test of the 200v turbine!
I continue the stress test with one 200v eco light bulb to measure the maximum output voltage and heat level of the 200v turbine.
I get more than 260v (so I have to use heavy cables) with 1 turbine,1 passive heat dissipator,1 furnace with combustion and 10% regulator,but the funniest thing was I put the signal trimmer only to 50% and I get that level of voltage,but the heat of the turbine was 650celsius and thats extreme,but after 650 it blows up! The maximum limit was 663celsius.
So you can overkill voltage it xd
I dont know is this a bug or something but I can't reach that kind of power whit other relases exept 1.4.6 or earlier! (But I liked that,because it gives more potencial  output power) 
![2014-08-12_22 27 49](https://cloud.githubusercontent.com/assets/8401485/3897221/db5bbf56-225f-11e4-9d1d-b6ca74104205.png)
The furnace maximum stabile heat was ~910 celsius whit combustion and regulator 10% .I think that is normal,it blows up at 914celsius.(I get that level in single furnace heating use,just the furnace nothing on the back)
Thanks for the lot of helps guys!

**Closed as completed** 2014-08-16 21:07 UTC
