### ISSUE TITLE
Power systems disappearing when machines have items in them during server restart.

### ISSUE THREAD

**Issue by omegahermit** [Electrical-Age/ElectricalAge#255] opened 2015-06-24 03:23 UTC
Hi all.

Recently upgraded to the latest version to try and get rid of this annoyance, no luck yet.  Everything works fine until my server restarts and then all of my machines, generators, wiring, anything connected to a machine disappear.  I should clarify that by items i mean anything in a plate machine, macerator, etc. or even the coils in my electric furnaces.  The blades of turbines and hydro generators are still in the game as null.tile.  Anyone else having this problem?  I didn't see one with this exact issue and was looking for a work around.  This mod has me the most excited about minecraft i have been since RP2 and i desperately need to play with it!  Thanks for any and all help.

Also have noted this appears in the console on the server approximately every 50-55 seconds.
[20:41:37] [Server thread/INFO] [STDOUT]: [mods.eln.node.NodeManager:saveToNbt:170]: WORLD SAVE 0
[20:41:37] [Server thread/INFO] [STDOUT]: [mods.eln.node.NodeManager:saveToNbt:170]: WORLD SAVE -1
[20:41:37] [Server thread/INFO] [STDOUT]: [mods.eln.node.NodeManager:saveToNbt:170]: WORLD SAVE 1
[20:41:37] [Server thread/INFO] [STDOUT]: [mods.eln.node.NodeManager:saveToNbt:170]: WORLD SAVE 7
[20:41:37] [Server thread/INFO] [STDOUT]: [mods.eln.node.NodeManager:saveToNbt:170]: WORLD SAVE -7
[20:41:37] [Server thread/INFO] [STDOUT]: [mods.eln.node.NodeManager:saveToNbt:170]: WORLD SAVE -100

Sorry it's not presented better, i'm such a rookie on here.. :<

**Comment by egeis** [comment] 2015-06-24 03:54
https://github.com/Dolu1990/ElectricalAge/issues/204

This is an old issue... We hoped we had a fix for it.

**Comment by omegahermit** [comment] 2015-06-24 04:00
As i read through the issues page a second time i did notice one similar to it but with no mention of it only happening when items were left in.  Possibly caused by the same issue?

Further testing produces no result, this problem seems to happen at random intervals.  I recreated my setup perfectly and had no problems whatsoever with anything disappearing, even with items in the furnace and with the furnaces running.  I did however have this happen multiple times 2 days ago.  I am at a loss for an explanation.

**Comment by bloxgate** [comment] 2015-06-24 07:18
I don't think the fork with the changes was ever pulled and Dolu1990's fix for it wasn't added AFAIK.

**Comment by Dolu1990** [comment] 2015-06-24 16:52
I had this problem to, some time i can reproduct the bug at 100 % rate, some time i just can't reproduct it XD

it seem it's a bad minecraft beavoral.

How do you restart your server ? do you close it cleanly ?

**Comment by Dolu1990** [comment] 2015-06-24 17:50
Good news, i get it.
So, Minecraft, in some bad way, call
    @SubscribeEvent
    public void onWorldSave(Save e) {

then 

```
@SubscribeEvent
public void onWorldUnload(Unload e) {
```

then one time again 

```
@SubscribeEvent
public void onWorldSave(Save e) {
```

But the problem is that i can't save a unloaded world <3
The worst at all is there is no console print when it do the seconde and sneaky save !

So i have fix it and will release the fix today.
Thanks for issues

**Closed as completed by Dolu1990** 2015-06-24 17:50 UTC
