### ISSUE TITLE
[Bug] Cable disconnects on server restart (advanced energy meter)

### ISSUE THREAD

**Issue by aschmois** [Electrical-Age/ElectricalAge#278] opened 2015-08-06 13:53 UTC
**Build r50**
Broken Connection:

![Broken Connection](http://i.imgur.com/27mU5RO.png)

Correct Connection:

![Correct Connection](http://i.imgur.com/C78kn8e.png)

Can be fixed by removing and adding the medium voltage cable in the meter's cable slot.

Un-hidden cables:
![Un-hidden Cables](http://i.imgur.com/dueKOQ1.png)

**Comment by aschmois** [comment] 2015-08-09 06:28
Update: The problem seems to be colored cables only. All cables that connect with a non-colored cable or a machine get disconnected on server restart

**Comment by cm0x4D** [comment] 2016-12-08 20:56
I could not reproduce the problem with the current version (1.13.0), so I close the issue, feel free to reopen it if you still have this issue with the actual version.

**Closed as completed by cm0x4D** 2016-12-08 20:56 UTC
Labels: bug
