### ISSUE TITLE
Lights not lighting

### ISSUE THREAD

**Issue by ghost** [Electrical-Age/ElectricalAge#539] opened 2016-11-24 17:38 UTC
when i turn on lights it doesn't actually give of light it just lights up, unless i place a block close enough to the light.
![2016-11-24_11 38 08](https://cloud.githubusercontent.com/assets/23726306/20607003/88a924de-b23a-11e6-937b-34c6f2bd5994.png)

**Comment by bloxgate** [comment] 2016-11-24 20:44
This looks like a duplicate of #474 and #505

**Comment by ghost** [comment] 2016-11-26 18:35
Also the flashlight is useless cause it has the same bug.

**Comment by cm0x4D** [comment] 2016-11-27 20:06
@judgedartist28 
Can you please provide more details about your setup?
MC version, Forge version and a list of all involved mods...

**Comment by ghost** [comment] 2016-11-28 03:40
I have 3 mods and 1 add on. The 3 mods are electrical age 1.12, buildcraft 7.1.17, and optifine 1.7.10 HD_U_D4 and the add on is DragonApi v16d
and im running mc 1.7.10 and forge is 10.13.4.1614

**Comment by ghost** [comment] 2016-11-28 03:50
After doing some testing it is in fact the DragonApi making it act up. Is there someway you can fix this with the next update? Or is this a problem with DragonApi itself that you can't fix

**Comment by bloxgate** [comment] 2016-11-28 04:08
Hmm, I think DragonAPI does some changes to how blocks set their light levels, and I have v15a installed in #474. Perhaps you should report this at [Reika's issue tracker](https://github.com/ReikaKalseki/Reika_Mods_Issues) too?

**Comment by ghost** [comment] 2016-11-28 04:09
I think i will

**Comment by ReikaKalseki** [comment] 2016-11-28 21:11
I do not change how light levels work. I do have a patch into setBlock to allow for choice of whether to cause lighting updates, but the default original method still triggers them, as is vanilla behavior. That is not the cause. Besides, that patch is disabled with FastCraft.

**Comment by bloxgate** [comment] 2016-11-29 01:32
@ReikaKalseki Well something in DragonAPI is still messing with Electrical Age's lights. Just tested this myself using only DragonAPI 16d and Electrical Age 1.12, **NO** FastCraft or Optifine.

Results w/ DragonAPI:
![Light switched on](https://gyazo.com/4b8ee1b31da1b4a60330d2857c7da984.gif)
![Block placed over light](https://gyazo.com/da9ef154902ab5a3a8c5b8199f82a0b0.gif)

Results w/out DragonAPI:
![Light switched on](https://gyazo.com/90051aef810a4f72a6e06e077da64e53.gif)

**Comment by Baughn** [comment] 2016-11-29 17:24
The lighting code in Eln is impenetrable enough that it may very well be buggy. Correlation does not imply causation, but if Reika has any ideas about what *might* be going on, I'm sure we'd be grateful.

**Comment by Baughn** [comment] 2016-11-29 17:24
And, oh yeah, duplicate.

**Closed as completed by Baughn** 2016-11-29 17:24 UTC

**Comment by ReikaKalseki** [comment] 2016-11-29 19:09
> if Reika has any ideas about what might be going on, I'm sure we'd be grateful.

The gif above almost made it look like block updates were involved, but the fact that breaking the grass block makes the light go dark again implies a problem with the native lighting code. I do nothing that would cause that sort of effect, and this is literally the first report of DragonAPI causing lighting issues *ever*. Unless you use entirely unique lighting code - and if you do, *that* may well be the source of the issue - if DragonAPI were broken it would affect all of vanilla as well.

**Comment by cm0x4D** [comment] 2016-11-29 23:04
I would try to reproduce the problem in our development environment, but I cannot find any dev version of DragonAPI to download, nor any information about how to actually build it (forge version, dependencies, ...). At least if I just add the code to our project I have quite a lot of compile errors due to missing dependencies. @ReikaKalseki could you give me some help here?

**Comment by judgedartist28** [comment] 2016-11-30 03:19
heres the link to download dragonapi: https://minecraft.curseforge.com/projects/dragonapi/files/2335800

**Comment by ReikaKalseki** [comment] 2016-11-30 20:44
There is no dev version of DragonAPI.

**Comment by cm0x4D** [comment] 2016-11-30 22:07
To bad. That would simplify my investigations...

Nevertheless I found something: In fact, the EA lightning code is even more than "a little special": The light is not placed directly at the lamp location - it is placed some blocks further, as long as there is no block in the way ([see here](https://github.com/Electrical-Age/ElectricalAge/blob/da56393b27beb72fd761a10aad6b7eb88fcafe30/src/main/java/mods/eln/sixnode/lampsocket/LampSocketProcess.java#L319-L370)). The light is only placed at the block location itself if there is a block directly in front of the lamp. So if the block is placed directly at the light source location, everything with DragonAPI is fine and it works. This explains the behavior in the videos above. If EA tries to place a light block at a different location, it fails if DragonAPI is loaded too. I do not know why, as I can not debug the code with DragonAPI. I suspect the problem somewhere [here](https://github.com/Electrical-Age/ElectricalAge/blob/16c8786795a60d819fcf905b0470d20d99be8130/src/main/java/mods/eln/sixnode/lampsocket/LightBlockEntity.java#L168-L180). If I comment out the code that actually moves the position of the light, there are no more problems with DragonAPI.

@Dolu1990 The reason to place the light at a different location is to simulate some kind of spotlight? Or why did you create the light at a different location?

**Comment by ReikaKalseki** [comment] 2016-12-01 20:51
Is the light a light block or an actual hack into the lighting engine?

**Comment by cm0x4D** [comment] 2016-12-01 21:07
Code is [here](https://github.com/Electrical-Age/ElectricalAge/blob/16c8786795a60d819fcf905b0470d20d99be8130/src/main/java/mods/eln/sixnode/lampsocket/LightBlock.java). Apparently it is a custom EA block.

**Comment by ReikaKalseki** [comment] 2016-12-01 23:10
Then I have no idea of the cause.
