### ISSUE TITLE
Odd character in lamp GUI tooltip.

### ISSUE THREAD

**Issue by DonBruce64** [Electrical-Age/ElectricalAge#769] opened 2017-10-01 04:08 UTC
Not sure what this is about.  I see an odd A in regular MC, and a smiley face when I use a Texture Pack with custom Unicode fonts.
![2017-09-30_23 03 06](https://user-images.githubusercontent.com/15241611/31051671-2e774ac4-a634-11e7-961d-8059fb5bdd27.png)

![2017-09-30_23 03 23](https://user-images.githubusercontent.com/15241611/31051670-2c651978-a634-11e7-9d7a-ef78149ad720.png)

**Comment by OmegaHaxors** [comment] 2017-10-01 09:12
It looks like a byte that's supposed to add a chat effect is mis-placed and spilling out into the string. I do believe this is fixed in the development version, so be patient for the fix.

**Comment by AMIDIBOSS** [comment] 2017-10-01 11:58
It makes me happy! Who doesn't want to see a smiley face?

**Comment by DonBruce64** [comment] 2017-10-01 15:55
There's a couple of other places where I've seen odd things like this.  I'll wait for the dev to drop as a release before reporting any others.

**Comment by cm0x4D** [comment] 2017-10-02 19:47
It seems to be fine in develop branch, so I close it for now. @DonBruce64 feel free to reopen this issue in case the problem is still in the next release.

**Closed as completed by cm0x4D** 2017-10-02 19:47 UTC
Labels: bug
