### ISSUE TITLE
bug infinite explosions

### ISSUE THREAD

**Issue by bjorguv** [Electrical-Age/ElectricalAge#642] opened 2017-02-07 23:16 UTC
VERSION 1.13
after breaking a few cables connected to a creative voltage thing. It started exploding infinitely until I shut the server off. It spammed my console with this message.

http://pastebin.com/du2e9cwS

**Comment by bjorguv** [comment] 2017-02-08 17:31
Is there a temporary fix for this because I really like your mod and would love to use it on my server but every time this happens it forces me to create a new map.

**Comment by cm0x4D** [comment] 2017-02-08 18:32
Why a new map? Can you not load the same map again?

**Comment by bjorguv** [comment] 2017-02-08 18:39
@cm0x4D I can but the explosions are infinite like I said. so when I load the world again the console is spammed VERY rapidly with that message I showed in pastebin. When I toggle explosions in the config file I am still spammed in the console.

**Comment by cm0x4D** [comment] 2017-02-08 18:48
Ok. This is strange. Normally after restarting the server or reloading the world, the problem is gone. Do you have a map with that problem? Could you send that map? This would really help to track the issue down.

**Comment by bjorguv** [comment] 2017-02-08 18:59
@cm0x4D Oh, I never actually tried to do either of those things. Sorry about that I misspoke in my response. I will try it now and get back to you.

Also do you know what causes this to happen? If so could you tell me so that I can avoid causing it in the future

**Comment by cm0x4D** [comment] 2017-02-08 19:01
Well it is a bug where a voltage watchdog is not destroyed along with the block when triggered. This happens very rarely, this is why we could not fix the bug yet.

**Comment by bjorguv** [comment] 2017-02-08 19:03
@cm0x4D Interesting it happened to me 4 times during a 3 hour period. any idea what could make it more frequent?

**Comment by cm0x4D** [comment] 2017-02-08 20:43
Do you remember what you exactly did in order to have this problem? 

I have found a problem with a race condition between the GUI and the simulation, but this means that there had to be items with a GUI and not just cables...

**Comment by bjorguv** [comment] 2017-02-08 21:08
@cm0x4D Oh yes, I seem to have left that part out. The only thing each case had in common was an Electrical Source and cable.

# GUIs INVOLVED

**in the first 2 occurences of the bug**
• _Experimental Transporter GUI_
• _Electrical source (creative energy block) GUI_

**last 2 occurrences**
• _Electrical source (creative energy block) GUI_
• _Lamp supply GUI_

**Comment by cm0x4D** [comment] 2017-02-20 06:08
Should be fixed in 1.14.0 - Feel free to reopen if it still happens.

**Closed as completed by cm0x4D** 2017-02-20 06:08 UTC
Labels: bug
