### ISSUE TITLE
Incompatability with certain mods in a modpack

### ISSUE THREAD

**Issue by PyroTheManiac** [Electrical-Age/ElectricalAge#722] opened 2017-04-16 21:12 UTC

**Comment by lrivard00** [comment] 2017-04-16 23:58
I have this same exact problem.
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 4/16/17 6:54 PM
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoSuchMethodError: net.minecraftforge.oredict.OreDictionary.doesOreNameExist(Ljava/lang/String;)Z
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:162)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:692)
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:288)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:541)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoSuchMethodError: net.minecraftforge.oredict.OreDictionary.doesOreNameExist(Ljava/lang/String;)Z
	at mods.eln.Eln.firstExistingOre(Eln.java:7534)
	at mods.eln.Eln.recipeTurbine(Eln.java:5667)
	at mods.eln.Eln.load(Eln.java:768)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:691)
	... 10 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_71, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 138322888 bytes (131 MB) / 529899520 bytes (505 MB) up to 4281597952 bytes (4083 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.82.1216 Minecraft Forge 10.13.1.1216 Optifine OptiFine_1.7.10_HD_U_C1 20 mods loaded, 20 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
	FML{7.10.82.1216} [Forge Mod Loader] (forge-1.7.10-10.13.1.1216-new.jar) Unloaded->Constructed->Pre-initialized->Initialized
	Forge{10.13.1.1216} [Minecraft Forge] (forge-1.7.10-10.13.1.1216-new.jar) Unloaded->Constructed->Pre-initialized->Initialized
	ArchitectureCraft{1.4.0} [ArchitectureCraft] (ArchitectureCraft-1.4.0-mc1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized
	CarpentersBlocks{3.3.7} [Carpenter's Blocks] (Carpenter's Blocks v3.3.7 - MC 1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized
	Eln{@VERSION@} [Electrical Age] (ElectricalAge-1.14.2.jar) Unloaded->Constructed->Pre-initialized->Errored
	flenixcities{0.11.1} [FlenixCities] (FlenixCitiesCore_[1.7.10]-0.11.1-b97.jar) Unloaded->Constructed->Pre-initialized->Initialized
	fc_research{0.4.0} [FlenixCities Research] (FlenixCitiesResearch_[1.7.10]-0.4 (1).jar) Unloaded->Constructed->Pre-initialized->Initialized
	GregsLighting{1.11.2} [Greg's Lighting] (GregsLighting-1.11.2-mc1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized
	malisiscore{1.7.10-0.12.5} [MalisisCore] (malisiscore-1.7.10-0.12.5.jar) Unloaded->Constructed->Pre-initialized->Initialized
	malisisdoors{1.7.10-1.9.3} [Malisis' Doors] (malisisdoors-1.7.10-1.9.3.jar) Unloaded->Constructed->Pre-initialized->Initialized
	Minema{v3.0-1.7.10} [Minema] (Minema-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized
	cfm{3.4.7} [§9MrCrayfish's Furniture Mod] (MrCrayfishFurnitureModv3.4.7(1.7.10).jar) Unloaded->Constructed->Pre-initialized->Initialized
	musiccraft{2.9.8} [MusicCraft] (musiccraft-2.9.8.jar) Unloaded->Constructed->Pre-initialized->Initialized
	NGTLib{1.7.10.4} [NGTLib] (NGTLib-1.7.10.zip) Unloaded->Constructed->Pre-initialized->Initialized
	RadixCore{2.1.3} [RadixCore] (RadixCore-1.7.10-2.1.3-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
	RTM{1.7.10.5} [Real Train Mod] (Real-Train-Mod-1.7.10 (2).zip) Unloaded->Constructed->Pre-initialized->Initialized
	secretroomsmod{4.7.1} [The SecretRoomsMod] (secretroomsmod-1.7.10-4.7.1.394.jar) Unloaded->Constructed->Pre-initialized->Initialized
	SlimevoidLib{2.0.4.7} [Slimevoid Library] (SlimevoidLibrary-2.0.4.7.jar) Unloaded->Constructed->Pre-initialized->Initialized
	worldedit{6.0-beta-01} [WorldEdit] (worldedit-forge-mc1.7.10-6.0-beta-01.jar) Unloaded->Constructed->Pre-initialized->Initialized

**Comment by bookerthegeek** [comment] 2017-04-17 00:16
Do us a favor and post those in a gist and then link them. Way to much to scroll through.

**Comment by bloxgate** [comment] 2017-04-17 02:19
Yes, a gist would be helpful. My first guess is that you have another mod using Kotlin with the same package structure as we do, but a different version of Kotlin.

**Comment by PyroTheManiac** [comment] 2017-04-17 02:24
what is a gist?

**Comment by bloxgate** [comment] 2017-04-17 02:25
It's like pastebin, but it's run by github. If you put that log into it, and simply link it, your post will be easier for us to read.
[Click here](https://gist.github.com)

**Comment by PyroTheManiac** [comment] 2017-04-17 02:26
the link says not found

**Comment by bloxgate** [comment] 2017-04-17 02:28
Hmm, try https://gist.github.com/

**Comment by PyroTheManiac** [comment] 2017-04-17 02:30
how would i paste the gist here?

**Comment by bloxgate** [comment] 2017-04-17 02:31
Just edit your original post to have a link to the gist instead of the log.

Also if possible, a link to the modpack itself so I can test some stuff would be helpful.

**Comment by PyroTheManiac** [comment] 2017-04-17 02:32
https://gist.github.com/PyroTheManiac/66f09eff93683db2cf679a4aa270a901 and https://www.technicpack.net/modpack/mats-techpack-1710.450813 for the modpack. did I do this gist right?

**Comment by PyroTheManiac** [comment] 2017-04-17 02:45
any progress?

**Comment by PyroTheManiac** [comment] 2017-04-17 04:07
what can I do to fix it on my end?

**Comment by bloxgate** [comment] 2017-04-17 04:27
You could build it using the changes from my PR, and then turn off ELN support in AOBD and the pack should load fine. Otherwise, you'll have to wait for a release with the fix in it.

**Comment by PyroTheManiac** [comment] 2017-04-17 04:30
what do you mean by PR?

**Comment by PyroTheManiac** [comment] 2017-04-17 04:40
thank you for your help but I'm going to wait for a response from an EA team member.

**Comment by bookerthegeek** [comment] 2017-04-17 07:09
@PyroTheManiac go [here][1] and install this mod into your pack, report back with the results please. Make sure to put BOTH the console log and the crash report into separate gists and link to those.

Also, please edit your previous posts to remove the log file and only leave the link to the gist please.

[1]:https://minecraft.curseforge.com/projects/yukarilib/files/2402809

**Comment by PyroTheManiac** [comment] 2017-04-17 15:16
how do i get the console log? technic launcher dosent have a console

**Comment by PyroTheManiac** [comment] 2017-04-17 15:19
@cm0x4D can you fix this problem in the next update of Electrical Age?

**Comment by PyroTheManiac** [comment] 2017-04-17 15:28
Console Log Gist-https://gist.github.com/PyroTheManiac/fde09b723ef574bb19c5ad117242269e 

Crash report- https://gist.github.com/PyroTheManiac/c8d8f29243ab17f813593716a71f8a39

**Comment by matru4** [comment] 2017-04-17 17:39
@PyroTheManiac I'm the modpack creator. I found what's causing the bug, It's the mod Botanical Addons remove the mod and it should work! Thanks to @bookerthegeek for suggesting to add YukariLib it has helped me find the bug.

**Comment by PyroTheManiac** [comment] 2017-04-17 18:05
I'll  be sure to do that but what exactly makes it conflict with electrical age?

**Comment by matru4** [comment] 2017-04-17 18:10
It  has to do with another mod using Kotlin with the same package structure as they do, but a different version of Kotlin. I don't really know what that means but Botanical Addons must be using a different version of Kotlin.

**Comment by PyroTheManiac** [comment] 2017-04-17 18:14
Maybe EA can add compatibility to work with BA because according to the Botanical Addons page its discontinued for 1.7 as of February 6, 2017.  so I do not believe the BA creator will add compatibility anytime soon

**Comment by matru4** [comment] 2017-04-17 18:18
That would be great if they can add compatibility with Botanical Addons. but for the time being I will remove Botanical Addons!

**Comment by cm0x4D** [comment] 2017-04-17 18:18
> @cm0x4D can you fix this problem in the next update of Electrical Age?

Yes, we try to fix it. We already have a PR from @bloxgate with a possible fix.

**Comment by PyroTheManiac** [comment] 2017-04-17 18:19
Ok thank you all for your help, should i close this issue now?

**Comment by cm0x4D** [comment] 2017-04-17 18:19
No, we will close it when it is actually fixed.

**Closed as completed** 2017-04-23 12:50 UTC
Labels: bug
