### ISSUE TITLE
NPE with version 1.14.2

### ISSUE THREAD

**Issue by pot-code** [Electrical-Age/ElectricalAge#755] opened 2017-08-14 04:43 UTC
Just keep getting NPE even without any other mods, detailed stacktrace is as follows:

```java
Stacktrace:
	at mods.eln.sixnode.diode.DiodeDescriptor.<init>(DiodeDescriptor.java:56)
	at mods.eln.Eln.registerPassiveComponent(Eln.java:1791)
	at mods.eln.Eln.preInit(Eln.java:577)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:556)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
```

```
-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_112, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 115320568 bytes (109 MB) / 259522560 bytes (247 MB) up to 4225236992 bytes (4029 MB)
	JVM Flags: 2 total; -Xincgc -Xmx4096M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 4 mods loaded, 4 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCH	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCE	Eln{@VERSION@} [Electrical Age] (ElectricalAge-1.14.2.jar) 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 382.05' Renderer: 'GeForce GTX 1070/PCIe/SSE2'
	Launched Version: 1.7.10-Forge10.13.4.1614-1.7.10
	LWJGL: 2.9.1
	OpenGL: GeForce GTX 1070/PCIe/SSE2 GL version 4.5.0 NVIDIA 382.05, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.
```

Dont know if I am the only lucky one

**Comment by cm0x4D** [comment] 2017-08-14 16:21
Hello @pot-code, could you try to reinstall the jar? It seems that some resources (3D models) can not be loaded which is an indication that the jar might be corrupt.

**Comment by pot-code** [comment] 2017-08-15 02:03
@cm0x4D Still no luck, not to mention I have done a compression test to the jar

_Sent from my Xiaomi Mi Note 2 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by cm0x4D** [comment] 2017-08-16 20:37
The 3D model for the Diode "PowerElectricPrimitives.obj" can not be loaded from the jar for whatever reason. Can you check the content of the jar file with:

```
# jar tf ElectricalAge-1.14.2.jar
```

and check that the following lines (along many others) are shown:

```
assets/eln/model/PowerElectricPrimitives/
assets/eln/model/PowerElectricPrimitives/PowerElectricPrimitives.obj
assets/eln/model/PowerElectricPrimitives/PowerElectricPrimitives.png
assets/eln/model/PowerElectricPrimitives/PowerElectricPrimitives.mtl
```

**Comment by pot-code** [comment] 2017-08-17 02:41
@cm0x4D Yes, they are present

That's fine, I have switched to ver.1.10.2 and will be waiting for Eln ;)

Thanks! 

_Sent from my Xiaomi Mi Note 2 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by cm0x4D** [comment] 2017-10-01 18:56
I was not able to reproduce, so I am closing it for now...

**Closed as completed by cm0x4D** 2017-10-01 18:56 UTC
Labels: bug

**Comment by AssasinAsha** [comment] 2018-08-08 20:29
I know this is old, but I encountered the same thing and for all the future people still playing 1.7.10 who get this error - check for non-letter characters in the modpack's filepath!
I installed a pack using MultiMC "install from zip" function and while making the pack folder, MultiMC replaced the spaces in the name with plus signs. That was enough to trip the mod which started throwing this error.
Swapping the plus signs for underscores did the trick.

**Comment by jrddunbr** [comment] 2018-08-08 22:22
Odd, because I use MuiltiMC w/o issue.

**Comment by AssasinAsha** [comment] 2018-08-08 22:25
... and you're right and I'm stupid.
There were no spaces in the pack's name, the pluses were there already, after download from curse.
So, yeah, I'm dumb. Sorry for wrong info on MultiMC.
At least I didn't screw up the filepath thing. ;)

**Comment by jrddunbr** [comment] 2018-08-08 22:42
~Interesting. CurseForge has spaces in the name?~
~I wonder how that causes a problem.~
We all make mistakes, is fine :)
