### ISSUE TITLE
ELN to other power converter block does not provide power to IEnergyReceiver

### ISSUE THREAD

**Issue by BionicFelps** [Electrical-Age/ElectricalAge#223] opened 2015-05-02 20:57 UTC
The power converter block is using an older version of the Thermal Expansion API, IEnergyHandlers work as expected, but IEnergyReceivers (new method) will not receive power.  A minor issue, but somewhat reduces the utility of the mod with respect to others!

Not really sure if this is true or not as I haven't looked at the code, but it would seem that way, as it doesn't power Mariculture items which are strictly IEnergyReceivers.

**Comment by lambdaShade** [comment] 2015-06-15 19:01
It's not a bug. It's a choice. You can power others mods with ELN, but not take power for others mods. Definitively won't fix - otherwise the mod progressively lose its coherence.

**Closed as completed** 2015-06-15 19:01 UTC
Labels: wontfix

**Comment by BionicFelps** [comment] 2015-06-28 20:09
... This is referring to blocks which will not ACCEPT energy FROM the ELN to other block, such as the Mariculture blocks such as the multiblock air compressor which generates air to use in scuba tanks.  I'm told that the blocks in question are coded as IEnergyReceivers, and not IEnergyHandlers.

Or are you saying it's intended that the ELN->Other block only provide energy to certain blocks based on implementation details that are invisible to end users?

To clarify, this is using the block as it is intended, as a one-way power converter from ELN to RF, and it is not working on certain things.
